# Persist data & logs
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Listen on all network interfaces, port 1883
listener 1883 0.0.0.0

# (DEV only) allow anonymous
allow_anonymous true
