
services:
  user-reg:
    build:
      context: ./flask-user-reg
      dockerfile: Dockerfile
    ports:
      - "8500:8000"                        # expose Flask on host:5002
    volumes:
      - ./flask-user-reg:/app             # live-sync your code
      - userreg-data:/app/subscribers.db  # persist the SQLite file
    environment:
      - WEBSOCKET_URL=ws://app:5000/ws  # adjust to whatever WS endpoint you need
      - FLASK_ENV=development
      - FLASK_APP=app.py
    
    networks:
      - app-network
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev   # Use a separate Dockerfile for development
    volumes:
      - ./frontend:/app            # Mount code for live reloading
      - /app/node_modules 
      # - ./frontend/build:/usr/share/nginx/html  # Serve static files 
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
      - WATCHPACK_POLLING=true    # Extra polling for webpack
      # - CONTAINER_ID=${HOSTNAME}
         # Avoid node_modules conflicts
    ports:
      - "3000:3000"                # Map directly to 3000 for development server
    command: ["npm", "start"]      # Use npm for hot reload
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped
  # Node.js/Express service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app 
      - /app/node_modules
    env_file:
      - ./backend/.env  # Load environment variables from .env file in backend directory
    ports:
      - '5000:5000' 
      
    depends_on:
      mongo:
        condition: service_healthy
      user-reg:
        condition: service_started   # waits for container to start (no health check)

    networks:
      - app-network
    restart: unless-stopped
    
    # MongoDB service
  mongo:
    image: mongo:8.0
    ports:
      - '27017:27017' 
    volumes:
      - mongo-data:/data/db
    command: ["--bind_ip_all"]
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:  # Ensure MongoDB is ready before the app starts
     test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
     interval: 10s
     timeout: 10s  # Increased timeout
     retries: 10   # More retries
     start_period: 30s  # Give MongoDB time to start
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  userreg-data:
  redis_data:
  mongo-data:
networks:
  app-network:
