
services:
  user-reg:
    build:
      context: ./flask-user-reg
      dockerfile: Dockerfile
    ports:
      - "8500:8500"                       
    volumes:
      - ./flask-user-reg:/app            
      - userreg-data:/app/subscribers.db  
    environment:
      - SOCKETIO_URL=http://app:5000
      - INTERNAL_SOCKET_SECRET=${INTERNAL_SOCKET_SECRET} 
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}             
      - FLASK_ENV=development
      - FLASK_APP=app.py
    depends_on:
      app:
        condition: service_started   

    networks:
      - app-network
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev   # Use a separate Dockerfile for development
    volumes:
      - ./frontend:/app            # Mount code for live reloading
      - /app/node_modules 
      # - ./frontend/build:/usr/share/nginx/html  # Serve static files 
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
      - WATCHPACK_POLLING=true    # Extra polling for webpack
      # - CONTAINER_ID=${HOSTNAME}
         # Avoid node_modules conflicts
    ports:
      - "3000:3000"                # Map directly to 3000 for development server
    command: ["npm", "start"]      # Use npm for hot reload
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped
  # Node.js/Express service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app 
      - /app/node_modules
    env_file:
      - ./backend/.env  # Load environment variables from .env file in backend directory
    environment:
      - INTERNAL_SOCKET_SECRET=${INTERNAL_SOCKET_SECRET}
    ports:
      - '5000:5000' 
    expose:
      - '5000'
    depends_on:
      mongo:
        condition: service_healthy
     
    networks:
      - app-network
    restart: unless-stopped
    
    
    # MongoDB service
  mongo:
    image: mongo:8.0
    ports:
      - '27017:27017' 
    volumes:
      - mongo-data:/data/db
    command: ["--bind_ip_all"]
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:  # Ensure MongoDB is ready before the app starts
     test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
     interval: 10s
     timeout: 10s  # Increased timeout
     retries: 10   # More retries
     start_period: 30s  # Give MongoDB time to start
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  userreg-data:
  redis_data:
  mongo-data:
networks:
  app-network:
