# docker-compose.yml
version: '3.8'

services:
# React.js service
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - app  
  #   networks:
  #     - app-network
  #   restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev   # Use a separate Dockerfile for development
    volumes:
      - ./frontend:/app            # Mount code for live reloading
      - /app/node_modules           # Avoid node_modules conflicts
    ports:
      - "3000:3000"                # Map directly to 3000 for development server
    command: ["npm", "start"]      # Use npm for hot reload
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped
  # Node.js/Express service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app 
      - /app/node_modules
    env_file:
      - ./backend/.env  # Load environment variables from .env file in backend directory
    ports:
      - '5000:5000' 
    depends_on:
      - mongo 
    networks:
      - app-network
    restart: unless-stopped
  # MongoDB service
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    
    ports:
      - '27017:27017' 
    volumes:
      - mongo-data:/data/db 
    command: ["--bind_ip_all"]
    networks:
      - app-network
    restart: unless-stopped
volumes:
  mongo-data:
networks:
  app-network:
